#!/bin/bash

#######################################################
#
# This is an init script for aerod, part of aerotools.
# (http://github.com/lynix/aerotools)
#
# It has been written for use with Arch Linux, but
# can be modified easily to fit other init systems.
#
#######################################################

. /etc/rc.conf
. /etc/rc.d/functions


# configuration
PORT=7635		                        # port to listen on, TCP
INTERVAL=10		                        # polling intrerval in seconds
AEROD="/usr/sbin/aerod"                 # path to binary


case "$1" in
	start)
		stat_busy "Starting aerod"
		PID=$(pidof -o %PPID $AEROD)
		if [ ! -z "$PID" ]; then
			stat_fail
			echo "$0: aerod seems to be already running"
			exit 1
		fi
		$AEROD -i $INTERVAL -p $PORT
		if [ $? -gt 0 ]; then
			stat_fail
			ck_daemon aerod || rm_daemon aerod
			exit 1
		fi
		stat_done
		ck_daemon aerod && add_daemon aerod
		;;
	stop)
		stat_busy "Stopping aerod"
		PID=$(pidof -o %PPID $AEROD)
		if [ -z "$PID" ]; then
			stat_fail
			echo "$0: failed to find aerod process"
            ck_daemon aerod || rm_daemon aerod
			exit 1
		fi
		kill $PID
		if [ $? -gt 0 ]; then
			stat_fail
			exit 1
		fi
		stat_done
		ck_daemon aerod || rm_daemon aerod
		;;
	restart)
		$0 start && sleep 2
		$0 stop
        exit $?
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
		;;
esac

exit 0
