#!/bin/bash
#
# Plugin to read values from aerod (part of aerotools)
#
# 2010 by lynix <lynix47@gmail.com>
#
#
# Magic markers - optional - used by installation scripts and
# munin-config:
#
#%# family=manual
#%# capabilities=autoconf

PORT=7635

MODE="$(echo "$0" | cut -d '_' -f 2)"
DATA="$(curl -s http://localhost:$PORT)"

if [ "$1" == "autoconf" ]; then
	echo "yes"
	exit 0
fi

if [ -z "$DATA" ]; then
	echo "unable to read from aerod"
	exit 1
fi


function get_name() {
	N=2
	ENTRY="$(echo "$DATA" | cut -d '|' -f $N)"
	while [ "$ENTRY" != "" ]; do
		if [ "$ENTRY" == "/dev/$1" ]; then
			break
		fi
		N=$((N + 5))
		ENTRY="$(echo "$DATA" | cut -d '|' -f $N)"
	done
	if [ "$ENTRY" == "/dev/$1" ]; then
		N=$((N + 1))
		echo "$DATA" | cut -d '|' -f $N
	else
		echo "unknown"
	fi
}

function get_value() {
	N=2
	ENTRY="$(echo "$DATA" | cut -d '|' -f $N)"
	while [ "$ENTRY" != "" ]; do
		if [ "$ENTRY" == "/dev/$1" ]; then
			break
		fi
		N=$((N + 5))
		ENTRY="$(echo "$DATA" | cut -d '|' -f $N)"
	done
	if [ "$ENTRY" == "/dev/$1" ]; then
		N=$((N + 2))
		echo "$DATA" | cut -d '|' -f $N
	else
		echo "unknown"
	fi
}


case "$MODE" in
	temp)
		case "$1" in
			config)
				echo "graph_title aerod temperatures"
		        echo "graph_args --base 1000 -l 0"
        		echo "graph_vlabel °C"
				echo "graph_scale no"
		        echo "graph_category Aquaero"
				GRAPH_ORDER=""
				for I in $(seq 6); do
					LABEL="$(get_name "temp$I")"
					if [ "$LABEL" != "unknown" ]; then
						GRAPH_ORDER="$GRAPH_ORDER temp$I"
						echo "temp$I.label $LABEL"
					fi
				done
				if [ "$GRAPH_ORDER" != "" ]; then
					echo "graph_order$GRAPH_ORDER"
				fi
				;;
			*)
				for I in $(seq 6); do
					VALUE="$(get_value "temp$I")"
					if [ "$VALUE" != "unknown" ]; then
						echo "temp$I.value $VALUE"
					fi
				done
				;;
		esac
		;;
	flow)
		case "$1" in
			config)
				echo "graph_title aerod flow"
		        echo "graph_args --base 1000 -l 0"
        		echo "graph_vlabel l/min"
				echo "graph_scale no"
		        echo "graph_category Aquaero"
        		echo "graph_order flow1"
		        echo "flow1.label $(get_name "flow")"
				;;
			*)
				echo "flow1.value $(get_value "flow")"
				;;
		esac
		;;
	fan)
		case "$1" in
			config)
				
				echo "graph_title aerod fan rpm"
		        echo "graph_args --base 1000 -l 0"
        		echo "graph_vlabel rpm"
				echo "graph_scale no"
		        echo "graph_category Aquaero"
				GRAPH_ORDER=""
				for I in $(seq 4); do
					LABEL="$(get_name "fan$I")"
					if [ "$LABEL" != "unknown" ]; then
						GRAPH_ORDER="$GRAPH_ORDER fan$I"
						echo "fan$I.label $LABEL"
					fi
				done
				if [ "$GRAPH_ORDER" != "" ]; then
					echo "graph_order$GRAPH_ORDER"
				fi
				;;
			*)
				for I in $(seq 4); do
					VALUE="$(get_value "fan$I")"
					if [ "$VALUE" != "unknown" ]; then
						echo "fan$I.value $VALUE"
					fi
				done
				;;
		esac
		;;
esac

exit 0
